### ISSUE TITLE
triangoli

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Triangoli#1]
![es4_16](https://cloud.githubusercontent.com/assets/3002194/14316282/8883c6ec-fc02-11e5-9c76-34f100878ebd.jpg)

**Comment by FabioZTessitore** [comment]
puoi usare i cicli for
devi creare un Makefile contenente la variabile CFLAGS

**Comment by FabioZTessitore** [comment]
che brutti cicli che hai fatto

**Comment by lucifero55** [comment]
Consigli?

**Comment by FabioZTessitore** [comment]
```C
for(conta = 0; altezza >= conta; conta++){
```
Se l'indice è `conta` perché la condizione è scritta come `altezza >= conta` e non come `conta<=altezza`? E' più chiaro mettere il contatore bene in evidenza.

```C
for(Num_ast = 0; conta != Num_ast; Num_ast++){
```
qui vale lo stesso discorso di prima e in più eviterei il `!=`. Meglio usare minore o maggiore

**Comment by lucifero55** [comment]
Aspetto
